In [2]:
import numpy as np
from datetime import date, timedelta

# 1. Create a 3x3x3 array with random values 

In [4]:
arr = np.random.rand(3,3,3)
arr

array([[[0.78946865, 0.65302502, 0.8395682 ],
        [0.80900463, 0.77036085, 0.29361485],
        [0.15068386, 0.1739047 , 0.3595728 ]],

       [[0.63632728, 0.8153752 , 0.76999912],
        [0.77341855, 0.23591134, 0.51867918],
        [0.3289677 , 0.08431707, 0.29070612]],

       [[0.88918781, 0.5751195 , 0.06201804],
        [0.97865164, 0.67964348, 0.03033718],
        [0.39507034, 0.03959   , 0.95089283]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [8]:
arr = np.random.rand(5,5)
arr = (arr - np.mean(arr))/np.std(arr)
arr

array([[ 0.89507602, -0.11219451,  1.19791715,  1.48124412, -0.19846496],
       [ 1.82367788, -0.13405331, -0.34629851, -0.8087071 , -0.95931552],
       [ 0.94660868,  1.89214611, -1.44835386, -1.16517778,  0.53951537],
       [-1.60724636, -1.36237321,  0.90482023, -0.26523583, -0.28228037],
       [ 0.39752159, -0.83440631, -0.95488938,  0.16306329,  0.23740654]])

# 5.  How to find common values between two arrays?

In [9]:
arr1 = np.random.randint(0, 10, 10)
arr2 = np.random.randint(0, 10, 10)
np.intersect1d(arr1, arr2)

array([0, 2, 7, 8])

# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
yest = np.datetime64('today') - np.timedelta64(1)
tod = np.datetime64('today') 
tom = np.datetime64('today') + np.timedelta64(1)
print(yest, tod, tom)

2020-08-19 2020-08-20 2020-08-21


# 7. Consider two random array A and B, check if they are equal

In [11]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)
print(arr1, arr2)
eq = np.array_equal(arr1, arr2)
print(eq)

[[0.90810437 0.34696394 0.62338416]
 [0.13317201 0.02244351 0.50928104]
 [0.59766451 0.11836756 0.9240337 ]] [[0.96169206 0.21148898 0.07597137]
 [0.0210993  0.5489518  0.0424537 ]
 [0.94073411 0.6964309  0.17520494]]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [12]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.        , 0.46439192, 0.39799822, 0.1861595 , 0.42077309,
       0.33811284, 0.56482749, 0.31405239, 0.74586188, 0.74296837])

# 9. How to print all the values of an array?

In [14]:
arr = np.random.rand(5,12)
print(arr)

[[0.51717333 0.71757299 0.31739601 0.00511287 0.33689426 0.79485112
  0.91517741 0.9641212  0.55029157 0.5444117  0.99979187 0.32680968]
 [0.35814158 0.29104909 0.26488618 0.02575666 0.02779592 0.02408094
  0.56566607 0.89949297 0.52836375 0.52370262 0.74324842 0.8021055 ]
 [0.98201968 0.47267471 0.24767289 0.36550649 0.79707711 0.34256971
  0.5404431  0.48105966 0.12178776 0.411035   0.0909539  0.90143938]
 [0.94015719 0.86072123 0.29803612 0.58609768 0.64550305 0.38056117
  0.38587507 0.35848395 0.28509952 0.26143731 0.40884114 0.2881746 ]
 [0.5127279  0.02508091 0.82811687 0.04929438 0.30013639 0.97003785
  0.16575358 0.95654992 0.61240414 0.28218491 0.75214224 0.92086175]]


# 10.Subtract the mean of each row of a matrix

In [15]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[ 0.00818394, -0.03406991,  0.02588597],
       [-0.2498547 ,  0.40147102, -0.15161632],
       [-0.34231169, -0.05072137,  0.39303306]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [16]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([2., 5., 2., 3., 3.])

# 12.How to get the diagonal of a dot product?

In [17]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([72, 27, 49])

# 13.How to find the most frequent value in an array?

In [19]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[8 4 8 8 6 0 6 4 1 2 1 2 2 2 3 7 2 6 6 0]


2

# 14.How to get the n largest values of an array

In [20]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

1

# 15.How to create a record array from a regular array?

In [22]:
ar1 = ['gauri', 'neha', 'pradnya']
arr = np.array(ar1)
print(ar1)
print(arr)

['gauri', 'neha', 'pradnya']
['gauri' 'neha' 'pradnya']
